apiVersion: batch/v1
kind: Job
metadata:
  name: fp-tree-main-experiment
  namespace: fp-tree
  labels:
    app.kubernetes.io/name: fp-tree-main-experiment
    app.kubernetes.io/part-of: fp-tree-ids
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fp-tree-main-experiment
        app.kubernetes.io/part-of: fp-tree-ids
    spec:
      restartPolicy: Never
      containers:
        - name: main
          image: fp-tree-ids:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          command: ["/bin/bash","-lc"]
          args:
            - >-
              python experiments/main_experiment_with_checkpointing.py --resume
          resources:
            requests:
              cpu: "2"
              memory: 4Gi
            limits:
              cpu: "4"
              memory: 8Gi
          volumeMounts:
            - name: results
              mountPath: /app/results
            - name: results
              mountPath: /app/checkpoints
              subPath: checkpoints
      volumes:
        - name: results
          persistentVolumeClaim:
            claimName: fp-tree-results

